[package]
name = "client-api"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.8", features = ["d3d9", "libloaderapi", "winuser", "winver"] }
retour = { version = "0.3", features = ["static-detour"] }
#retour = { git = "https://github.com/Hpmason/retour-rs" }
log = "0.4.14"
